### ISSUE TITLE
Frameworks built with Xcode 7 give many errors when linked in Xcode 7

### ISSUE THREAD

**Issue by jtreanor** [CocoaPods/cocoapods-packager#101]
When any framework built with CocoaPods Packager + Xcode 7 is integrated in an Xcode 7 project with "Debug Information Format" set to "DWARF with dSYM", there are many warnings given. Here is a sample from [NikeKit](https://github.com/neonichu/NikeKit):

![screen shot 2015-09-23 at 15 12 53](https://cloud.githubusercontent.com/assets/1773641/10047338/9e0bea54-6205-11e5-9160-7152512973c7.png)

**Note:** "DWARF with dSYM" was the default prior to Xcode 7 so almost every project will have this issue.

**Steps to reproduce:**

This example uses NikeKit but it happens for every Pod I have tried (AFNetworking etc.)

1. `git clone git@github.com:neonichu/NikeKit.git`
2. `cd NikeKit`
3. `pod package NikeKit.podspec --no-mangle` (I only specify no mangle here to demonstrate mangling is not the issue).
4. Either delete the contents of `/var/folders/` or do the remaining steps on a different machine.
5. Drag `NikeKit.framework` in you Xcode 7 project with "Debug Information Format" set to "DWARF with dSYM".
6. `#import <NikeKit/BBUNikePlusActivity.h>` and call `[BBUNikePlusActivity new];` somewhere.
7. Build & run.

**Comment by neonichu** [comment]
Might be worth creating a radar for?

**Comment by jtreanor** [comment]
@neonichu You're probably right, I'll write on up this evening.

However, I'm not quite convinced this is all Xcode's fault. There are numerous static Frameworks around that have been built on Xcode 7 and don't cause warnings (HockeyApp comes to mind). So there must be some way to work around this.

**Comment by neonichu** [comment]
I'll try to repro it w/o CocoaPods as well — maybe turning off dSYM creation when building the libs helps?

**Comment by jtreanor** [comment]
@neonichu I have reproduced both with and without CocoaPods but its certainly useful to confirm.

Good idea. I'll try turning off dSYM creation.

**Comment by jtreanor** [comment]
`config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'` in `pod_utils.rb` didn't help unfortunately.

**Comment by jtreanor** [comment]
I have managed to fix this by setting:

```
config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
```

I'm not fully sure of the consequences of this but it looks like out only option. I'll cut a PR.

**Comment by neonichu** [comment]
awesome — still seems like this is a worth a radar since it looks like a Xcode 7 regression.

**Comment by jtreanor** [comment]
@neonichu Yes, absolutely. I'll post it here.

**Comment by neonichu** [comment]
:+1:

**Comment by agarwalswapnil** [comment]
I faced the same problem while trying to manully integrate a library(.lib) in a Xcode project. This worked for me, though I had to spent around 5 hours. @jtreanor thank you.

**Comment by jtreanor** [comment]
@agarwalswapnil You're welcome :smile:

**Comment by leviyehonatan** [comment]
i would like to use this fix it seems 1.3.0 does not include this is there a way to install a snapshot version of the packager?

**Comment by neonichu** [comment]
I'll make a new release, it's time anyway :)

**Comment by neonichu** [comment]
At an impasse for a new release right now, because there seems to be a test suite regression when using CP 0.39 which I don't have time to debug right now. 

You can install `master` yourself, though, by checking out the repo and running:

- `rake install` if you use any kind of custom ruby
- or ```
$ rake build
$ sudo gem install pkg/cocoapods-packager-1.3.0.gem``` if you are using system ruby.

**Comment by leviyehonatan** [comment]
any estimate on that?

**Comment by neonichu** [comment]
Since CP 1.0 is close, I'll probably just update to that, so it'll be a few weeks.

**Comment by leviyehonatan** [comment]
so i have to revert to 0.38 of CP to run the master branch?
— Yehonatan
leviyehonatan@gmail.com

**Comment by neonichu** [comment]
I'm not sure, as said above a test suite regression happens with 0.39, but that doesn't necessarily mean that there is an actual regression or that you would hit it. Might make sense to just try and see if it works fine for you with 0.39

**Comment by leviyehonatan** [comment]
any news about this?
