### ISSUE TITLE
pod package fail

### ISSUE THREAD

**Issue by ajitam** [CocoaPods/cocoapods-packager#105]
Hi,

I'm having problem building framework of my SDK. The thing is that lately a few POD have been updated and I'm not shore what is causing the problem, so I want to apologies in advance if this is not 'cocoapods-packager' fault.

So I have a SDK which is working find not compressed into framework. When I run

    pod package MySDK.podspec

I get

```
Analyzing dependencies
Fetching podspec for `MySDK` from `MySDK.podspec`
Downloading dependencies
Installing AFNetworking (2.6.1)
Installing MySDK (0.8.7)
Installing CocoaLumberjack (2.0.3)
Installing Realm (0.96.0)
Generating Pods project
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
Building framework
Build command failed: xcodebuild GCC_PREPROCESSOR_DEFINITIONS='PodsDummy_Pods_MySDK=PodsDummy_PodPackage_MySDK'  ARCHS="x86_64 i386 arm64 armv7 armv7s" CONFIGURATION_BUILD_DIR=build clean build  -configuration Release -target Pods -project Pods/Pods.xcodeproj 2>&1
Output:
    2015-10-21 11:23:01.341 xcodebuild[69747:16720260] [MT] PluginLoading: Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    Build settings from command line:
        ARCHS = x86_64 i386 arm64 armv7 armv7s
        CONFIGURATION_BUILD_DIR = build
        GCC_PREPROCESSOR_DEFINITIONS = PodsDummy_Pods_MySDK=PodsDummy_PodPackage_MySDK

    === CLEAN TARGET AFNetworking OF PROJECT Pods WITH CONFIGURATION Release ===
```

So here I can see that something is wrong with Realm.

And the end of output

```
    ** BUILD FAILED **


    The following build commands failed:
      CompileC /var/folders/py/h81xqj24x155fxfjxp6w8w0000/T/cocoapods-ezt6xueu/build/Pods.build/Release-iphoneos/MySDK.build/Objects-normal/arm64/TaskManager.o MySDK/Code/Core/Managers/TaskManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
      CompileC /var/folders/py/h81xqj24x155fxfjxp6w8w0000/T/cocoapods-ezt6xueu/build/Pods.build/Release-iphoneos/MySDK.build/Objects-normal/arm64/SomeObject.o MySDK/Code/Objects/SomeObject.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (2 failures)
```

**Comment by neonichu** [comment]
Can't say anything with the truncated output, you'll have to dig up the actual build errors from the full output.

**Comment by ajitam** [comment]
I manage to fix almost all issues and now I can build framework (--no-mangle). If I enable mangle I get:

```
Building framework
Mangling symbols
Building mangled framework
Build command failed: xcodebuild GCC_PREPROCESSOR_DEFINITIONS='${inherited} PodsDummy_MySDK=PodMySDK_PodsDummy_MySDK AFHTTPRequestOperation=PodMySDK_AFHTTPRequestOperation ...
```

 And all files are there. Any idea how I can get more into this error? I tried --verbose but I dont get anything more

**Comment by ajitam** [comment]
I limit down this error to Realm so I posted issue there

**Comment by ajitam** [comment]
Hi, I just wanted to update this issue. As it turns out in the end the problem was (is still is) in... xCode :)
The thing is that if I rollback Realm version to 0.95.0 it works and for 0.95.3 it doesn't - but not because of anything **in** the code. Problem is the **length** of code.

I managed to found the error: `Argument list too long`

That means that new version of Realm has increase number of methods that needs to be mangled and it is to much for xCode build process.

I confirmed that by including the 0.95.0 version and then including another POD - which produced the same error.

**Comment by lllhf** [comment]
@ajitam same error occur to me. Could u please provide the solution for me? thx a lot :)

**Comment by ajitam** [comment]
Well error is 6 years old :) sooooo you guess is as good as mine :)
But from my last post you can see that the problem was in mangling of the code - that is a fact which cannot be changed.

**Comment by lllhf** [comment]
sooooo sad :(
thx for ur quick reply!
