### ISSUE TITLE
pod package success，but framework has no content

### ISSUE THREAD

**Issue by QF-ZhouCheng** [CocoaPods/cocoapods-packager#109]
I use 'pod package' to generate my new framework, and it succeed, but the result folder has a spare folder 'build', and when i use the framework in one project, caught a error show the framework can not be found, the framework file is strange, generally, it should be 12 MB, but now only 109KB, how is it?

Any advice will be appreciate, thanks in advance!

**Comment by neonichu** [comment]
Do you receive any errors while you're packaging? Can you share an example project?

**Comment by QF-ZhouCheng** [comment]
Forgot to sync the fix information. I have fixed this issue. At first the cocoapods gem I use is 0.38.2, and the cocoapods-packagers gem version is 1.2.1,when i update the version of cocoapods to 0.39.0 and cocoapods-packager's version to 1.3.0, the issue was fixed, but I don't know what change of the new cocoapods caused the issue. Appreciate the help from @YoungShook
