### ISSUE TITLE
Resources are not copied

### ISSUE THREAD

**Issue by johanrydenstam** [CocoaPods/cocoapods-packager#112]
Resource/resources defined in `podspec` are not copied.

When adding something like
``` s.resource = 'Pod/Assets/Info.plist'```
to the podfile a `Resource` folder is created in the Framework but it remains empty.

`pod package XYZ.podspec` also generates a message saying:
`usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory`

**Comment by neonichu** [comment]
Did you validate the podspec? This sounds like the resource is not found.

**Comment by johanrydenstam** [comment]
Yes, I did validate it.

And the resource is included when using it as a non-framework pod

**Comment by neonichu** [comment]
Unfortunately, I could not reproduce it with a quick generic test myself, so I'd need a concrete project where this happens to investigate further.

**Comment by neonichu** [comment]
Closing because of lack of response.
