### ISSUE TITLE
Framework seems to build ok, but can't make imports work

### ISSUE THREAD

**Issue by ExoticObjects** [CocoaPods/cocoapods-packager#120]
I forked the two projects referenced [here](https://github.com/CocoaPods/cocoapods-packager/issues/82) to test basic functionality of cocoapods-packager. I'm sure it works fine, but I can't successfully import and use the framework I've compiled. A bit more documentation would be nice. Once I figure out how to make it work I'll add some and submit a pull request...

Here are the projects:

* [Test Framework Source](https://github.com/ExoticObjects/TestFramework)
* [Test Framework Compiled](https://github.com/ExoticObjects/TestFrameworkCompiled)
* [Test Framework Consumed](https://github.com/ExoticObjects/TestLibraryConsumer)

The Podfile in the third project allows you to switch between using the source files and using the compiled framework:

```ruby
platform :ios, '9.0'
use_frameworks!

target :TestLibraryConsumer do

  # build from source - import in AppDelegate compiles fine
  # pod 'TestLibrary', :git => 'https://github.com/ExoticObjects/TestFramework.git'

  # build from framework compiled from that source - import in AppDelegate does not compile
  pod 'TestLibrary', :git => 'https://github.com/ExoticObjects/TestFrameworkCompiled.git'

end
```

The test code is in `application:didFinishLaunchingWithOptions` The import statement looks like this:

`#import <TestLibrary/TestClass.h>`

That works fine when using source. When using the framework, however, Xcode won't compile the project. I'm not sure if the import needs to change in order to use the framework?

Here's the error:

```ruby
Undefined symbols for architecture x86_64:
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[AFNetworkReachabilityManager managerForAddress:] in TestLibrary(AFNetworkReachabilityManager.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[AFNetworkReachabilityManager managerForDomain:] in TestLibrary(AFNetworkReachabilityManager.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      ___47-[AFNetworkReachabilityManager startMonitoring]_block_invoke.52 in TestLibrary(AFNetworkReachabilityManager.o)
  "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
      -[AFNetworkReachabilityManager startMonitoring] in TestLibrary(AFNetworkReachabilityManager.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[AFNetworkReachabilityManager startMonitoring] in TestLibrary(AFNetworkReachabilityManager.o)
  "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
      -[AFNetworkReachabilityManager stopMonitoring] in TestLibrary(AFNetworkReachabilityManager.o)
  "_UTTypeCopyPreferredTagWithClass", referenced from:
      -[AFStreamingMultipartFormData appendPartWithFileURL:name:error:] in TestLibrary(AFURLRequestSerialization.o)
  "_UTTypeCreatePreferredIdentifierForTag", referenced from:
      -[AFStreamingMultipartFormData appendPartWithFileURL:name:error:] in TestLibrary(AFURLRequestSerialization.o)
  "_kUTTagClassFilenameExtension", referenced from:
      -[AFStreamingMultipartFormData appendPartWithFileURL:name:error:] in TestLibrary(AFURLRequestSerialization.o)
  "_kUTTagClassMIMEType", referenced from:
      -[AFStreamingMultipartFormData appendPartWithFileURL:name:error:] in TestLibrary(AFURLRequestSerialization.o)
```
I'm not sure why these files wouldn't be in the compiled framework or how to go about fixing it. Xcode also gives a warning that is probably more to the point:

```ruby
TestLibraryConsumer/AppDelegate.m:6:2: Missing submodule 'TestLibrary.TestClass'
```

I've built the framework with and without mangling - which I've read about but don't claim to understand - using a command like this:

`pod package TestLibrary.podspec --embedded --no-mangle --force `

To be honest, I'm feeling my way around in the dark. Any advice would be helpful! Thanks...

**Comment by wonc003** [comment]
I've having the same issue, tried setting valid architectures in the generated pod project, tried including multiple platforms.

**Comment by neonichu** [comment]
The missing symbols are from `SystemConfiguration` and `CoreServices`/`MobileCoreServices` system frameworks. Those not being carried over to the generated podspec is a known issue #67, you can have a look at the AFNetworking podspec on how to add them.

**Comment by wonc003** [comment]
My problem is a little different. My pod does not contain any dependencies and I get the following error when building:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DATGClientlessAdobePass", referenced from:
      objc-class-ref in AuthManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ExoticObjects** [comment]
Thanks! Works now. I'll submit a PR soon.

**Comment by neonichu** [comment]
@ExoticObjects awesome :+1:
