### ISSUE TITLE
Packager not creating any headers

### ISSUE THREAD

**Issue by ExoticObjects** [CocoaPods/cocoapods-packager#121]
Using the test projects I created [in this ticket](https://github.com/CocoaPods/cocoapods-packager/issues/120):

* [Test Framework Source](https://github.com/ExoticObjects/TestFramework)
* [Test Framework Compiled](https://github.com/ExoticObjects/TestFrameworkCompiled)
* [Test Framework Consumed](https://github.com/ExoticObjects/TestLibraryConsumer)

...when I run the packager it creates some header files in `TestLibrary.framework/Headers` and  `TestLibrary.framework/Versions/A/Headers`. 

```ruby
TestClass.h
TestLibrary.h
```

These are obviously essential - without them you can't import the framework!

My goal was to take what I learned in that simple test and apply it to a much larger framework I'm trying to package. But when I run the packager on my lib it doesn't create any header files. There are no error messages - it indicates success. Just no headers. So then I can't import anything :-(

The TestFramework source has [these](https://github.com/ExoticObjects/TestFramework/tree/master/TestLibrary) files at the top level. 

I have a similar header and about three hundred files in folders nested inside my top level folder. I don't have the plist...

What am I doing wrong? What would cause no headers to be copied to the Headers directories? I don't think I need to list my headers using `public_headers`, as I've read that if I don't do this they're all public (good enough for now...)

**Comment by neonichu** [comment]
Are you able to share the podspec used for this?

**Comment by ExoticObjects** [comment]
It's currently in a private repo and the podspec points to a few other private repos, but here it is for the most part. Nothing fancy at all:

```ruby

Pod::Spec.new do |s|
  s.name = 'EOLibrary'
  s.module_name = 'EOLibrary'
  s.summary = "Exotic Objects iOS lib"
  s.version = '1.0.0' 
  s.platform = :ios, '9.0'
  s.ios.deployment_target = '9.0'
  s.homepage = "http://exoticobjects.com"
  s.source = {:git => "git@github.com:****/****.git"} # private repo
  s.requires_arc = true
  s.source_files = 'Pod/Classes/**/*.{h,m}'
  s.exclude_files = 'Pod/Classes/spec/**/*.{h,m}', 'Pod/Classes/deprecated/**/*.{h,m}'
  # s.public_header_files = 'Pod/Classes/**/*.h'

  # Cocoapods-packager doesn't pull in frameworks in dependencies. So we need to do that manually.
  # Adding them here, as packager auto-creates podspec. If they're here, it will pick them up. 
  # See: https://github.com/CocoaPods/cocoapods-packager/issues/120 and https://github.com/CocoaPods/cocoapods-packager/issues/67
  s.ios.frameworks = ['CoreData','CoreGraphics','CoreImage','CoreLocation','CoreText','Foundation','ImageIO','MapKit','MessageUI','MobileCoreServices','QuartzCore','Security','SystemConfiguration','UIKit']
  s.license = 'MIT'

  s.dependency 'NGAParallaxMotion', '1.0.2'
  s.dependency 'Igor', '0.5.0'
  s.dependency 'UICKeyChainStore', '1.0.5'
  s.dependency 'AFNetworking', '2.5.2'
  s.dependency 'STHTTPRequest', '1.1.0'
  s.dependency 'SDWebImage'
  s.dependency 'SVProgressHUD', '1.0'
  s.dependency 'ReactiveCocoa', '2.1.8'
  s.dependency 'BlocksKit', '2.2.5'
  s.dependency 'handlebars-objc', '1.4.4'
  s.dependency 'FontAwesome+iOS', '0.1.4'
  s.dependency 'FontAwesomeTools', '1.2'
  s.dependency 'ActiveRecord', '1.2.2'
  s.dependency 'UIView+AutoLayout'
  s.dependency 'SimulatorStatusMagic', '1.7'

  # private pod (resolved with 'source' directive in Podfile)
  s.dependency 'eo-attributed-markdown'

  # private pod (resolved with 'source' directive in Podfile)
  s.dependency 'FMDB'

end
```

**Comment by neonichu** [comment]
Yah, nothing fancy I can see — does running `pod spec lint` on it show anything?

**Comment by ExoticObjects** [comment]
What's odd is that this library compiles and my app runs fine. But (as I just found out) it doesn't lint. And now that I've 'fixed' some of the problems, the package doesn't build anymore.

So, I'm guessing failure to lint would result in lack of headers?

**Comment by ExoticObjects** [comment]
Well, it was building, but lint fails. That's led me to find some real errors that need fixing, I guess, even though Xcode uses the same library then compiling my test app and it works fine.

I realize this is now a new topic, but I'm getting errors like this:

```ruby
ld: file not found: /var/folders/kc/yjptvb514c35mzw3rz9bs4f80000gn/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/Jalapeno.build/Objects-normal/i386/EOSetup.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Not sure what to make of that...

**Comment by neonichu** [comment]
Can you provide more of the build log? I'm assuming building `EOSetup.o` fails before this error.

**Comment by ExoticObjects** [comment]
You're right! Thanks, I've got it building now... Somehow the (literally) 50,000 lines of output from Xcode makes it hard to know what went wrong...
