### ISSUE TITLE
Framework built for tvOS does not run on tvOS Simulator

### ISSUE THREAD

**Issue by wonc003** [CocoaPods/cocoapods-packager#122]
When defining the platform in the podspec as :tvos, the framework generate will run fine on the device but when I try to run the project on the tvOS simulator the project fails to build with the following error:

"file was built for archive which is not the architecture being linked (x86_64)"

If I change the platform to ios in the podspec I can use the framework to run on the tvOS simulator but have the opposite problem when trying to run on device. 

So looks to me that the framework being built for tvOS does not include tvOS simulator symbols. But i'm taking shot in the dark at this point.

**Comment by neonichu** [comment]
This is a known issue, see #103 — fat binaries are only build correctly for iOS at the moment.
