### ISSUE TITLE
Pods or frameworks inside frameworks

### ISSUE THREAD

**Issue by ExoticObjects** [CocoaPods/cocoapods-packager#124]
So, if I'm just using Cocoapods normally and I have a local development pod that has some dependencies on, say, AFNetworking, I can import a class from my local pod like this:

`#import <MyPod/MyClass.h>` 

and from AFNetworking like this:

`#import <AFNetworking/AFNetworking.h>`

After packaging up that same local pod using Cocoapods-packager, the imports for my development pod still work, but I can't figure out how to import AFNetworking (or any other dependency). 

I've tried these:
`#import <AFNetworking/AFNetworking.h>`
`#import "SomeAFNetworkingClass.h"`
`@import AFNetworking`

None of these work...

I realize that Cocoapods Rome might be better suited for what I want to do, but is there any way to get this done with the packager? Thanks...

**Comment by neonichu** [comment]
No, this is intentionally not possible with cp-packager, headers of dependencies are never exported.
