### ISSUE TITLE
How to bundle a third party .a?

### ISSUE THREAD

**Issue by djMax** [CocoaPods/cocoapods-packager#129]
I have a podspec that includes a vendored .a library. I want that .a in my final output but "invisible" to the user - i.e. I want it bundled in my binary. In our old jverkoey-based framework scripts this worked. I think it worked because OUR stuff was in a .a, and that .a included the vendor .a inside. How can I do the same thing with cocoapods-packager?

**Comment by neonichu** [comment]
Unfortunately, this is not supported right now, see #26

**Comment by djMax** [comment]
Does that imply --no-mangle DOES lipo them in now?

**Comment by djMax** [comment]
Looks like manual lipo could do it, which would be fine for me.

**Comment by djMax** [comment]
Actually, I guess it wouldn't be lipo, it might be libtool?

**Comment by neonichu** [comment]
Right, `libtool` would be the way to go, similar to how it is currently used internally: https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/builder.rb#L128

**Comment by djMax** [comment]
Looks like libtool comes before lipo, I assume by necessity? So I end up having to unpack and repack... Fun.
