### ISSUE TITLE
Can't use framework made with packager as a dependency in a podspec

### ISSUE THREAD

**Issue by ExoticObjects** [CocoaPods/cocoapods-packager#130]
* Made the simplest possible framework - one class with one method, no dependencies. 
* Packaged it up like this: 

```ruby
pod package pod_a.podspec --embedded --force --verbose --no-mangle
```
* I can use this framework from my appDelegate
* If I try to declare the framework as a dependency in another pod, I get the `target has transitive dependencies that include static binaries` error.
* I can make the error go away using `verify_no_static_framework_transitive_dependencies`, but then I get other errors anyway, so I think I should figure out why I'm getting this error.

The error seems odd to me, as I was under the impression that cocoapods packager made dynamic frameworks and not static libraries when I use the `--embedded` switch. [This issue](https://github.com/CocoaPods/CocoaPods/issues/3841) seems relevant, but again, I don't know why cocoapods would think my dynamic framework was a static library.

I made a [test project](https://github.com/ExoticObjects/test_sibling_dependencies) to show the problem.

**Comment by ExoticObjects** [comment]
If I run this

```ruby
pre_install do |installer|
  # workaround, see https://github.com/CocoaPods/CocoaPods/issues/3289
  def installer.verify_no_static_framework_transitive_dependencies; end
end
```

then I end up getting errors like this 

```ruby
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PodAHelper", referenced from:
      objc-class-ref in PodBHelper.o
ld: symbol(s) not found for architecture x86_64
```

which indicates that pod_b doesn't have access to the framework in pod_a.

Any idea what I might be doing wrong?

**Comment by segiddins** [comment]
@ExoticObjects that's why that check for transitive static deps exists :)

**Comment by ExoticObjects** [comment]
Can you explain why the framework I made with the packager is a transitive
dependency?

**Comment by segiddins** [comment]
`--embedded` makes it a static framework, iirc

**Comment by ExoticObjects** [comment]
I'm thankful for the info! I'll give it a try. 

FWIW, the documentation on this could, well, be better. 

Here's what `pod packager --help` returns that might be relevant:

```ruby
    --embedded                                                      Generate embedded
                                                                    frameworks.
    --library                                                       Generate static
                                                                    libraries.
```

And here are some decent definitions of the pertinent terminology from [here](http://code.hootsuite.com/an-introduction-to-creating-and-distributing-embedded-frameworks-in-ios/):

* Static frameworks are linked at compile time. Dynamic frameworks are linked at runtime, and can be modified without relinking.
* Embedded frameworks are placed within an app’s sandbox and are only available to that app. System frameworks are stored at the system-level and are available to all apps. 

So, given the switches provided, I'm not sure what switches I should use to create a dynamic embedded framework. I will always want to make an embedded framework, and it seems unfortunate that that means my framework will be static.

* Use `--embedded`: framework is static and can't be used as a dependency. 
* Don't use `--embedded`: framework is dynamic (that means that dynamic is the default), but is a system framework that can be used by any app. There are cases where I'd want to do that, but this isn't one of them.

Maybe there's a nuance here that I'm not getting? Maybe dynamic frameworks HAVE to be system frameworks?

At any rate, I think the `--help` should be augmented to deal with some of these nuances. I realize that I can submit a pull request, but my understanding of the topics, though continually improving, is still pretty thin.

**Comment by ExoticObjects** [comment]
After packaging without using the `--embedded` flag, I still have the same problem. 

The [very simple test project](https://github.com/ExoticObjects/test_sibling_dependencies) is still available. I'd love to know what I'm doing wrong!

**Comment by neonichu** [comment]
You need the `--dynamic` flag to create a dynamic framework. The `--embedded` flag only changes the packaging structure, not the type of binary being produced.

**Comment by ExoticObjects** [comment]
Great to know! Wish I'd known that two weeks ago :-(

This is the full output of `pod package --help`:

```ruby
    --force                                                         Overwrite existing
                                                                    files.
    --no-mangle                                                     Do not mangle
                                                                    symbols of
                                                                    depedendant Pods.
    --embedded                                                      Generate embedded
                                                                    frameworks.
    --library                                                       Generate static
                                                                    libraries.
    --subspecs                                                      Only include the
                                                                    given subspecs
    --spec-sources=private,https://github.com/CocoaPods/Specs.git   The sources to
                                                                    pull dependant
                                                                    pods from
                                                                    (defaults to
                                                                    https://github.com/CocoaPods/Specs.git)
```

Any reason not to include the `--dynamic` flag in there?

**Comment by ExoticObjects** [comment]
Also, when I try to pass in `--dynamic` I get an error:

```ruby
pod package test_sibling_dependencies_pod_a.podspec --embedded --force --dynamic
[!] Unknown option: `--dynamic`
```

I can see the dynamic option listed in package.rb:

```ruby
def self.options
  [
    ['--force',     'Overwrite existing files.'],
    ['--no-mangle', 'Do not mangle symbols of depedendant Pods.'],
    ['--embedded',  'Generate embedded frameworks.'],
    ['--library',   'Generate static libraries.'],
    ['--dynamic',   'Generate dynamic framework.'],
    ['--subspecs',  'Only include the given subspecs'],
    ['--spec-sources=private,https://github.com/CocoaPods/Specs.git', 'The sources to pull dependant ' \
      'pods from (defaults to https://github.com/CocoaPods/Specs.git)'],
  ]
end
```

but it doesn't show up when I use `pod package --help`, and doesn't work in the code above.

Perhaps something is wrong with my cocoapods-packager installation?

**Comment by ExoticObjects** [comment]
Aha, my installed version of cocoapods-packager (at `~/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb`) lists the options without `--dynamic`:

```ruby
def self.options
  [
    ['--force',     'Overwrite existing files.'],
    ['--no-mangle', 'Do not mangle symbols of depedendant Pods.'],
    ['--embedded',  'Generate embedded frameworks.'],
    ['--library',   'Generate static libraries.'],
    ['--subspecs',  'Only include the given subspecs'],
    ['--spec-sources=private,https://github.com/CocoaPods/Specs.git', 'The sources to pull dependant ' \
      'pods from (defaults to https://github.com/CocoaPods/Specs.git)'],
  ]
end
```

while the source that I checked out lists the --dynamic option.

I'm not a ruby developer, so I'm not sure how to update the gem to the latest. I have 1.3.0, which I believe IS the latest:

```ruby
gem search cocoapods-packager

*** REMOTE GEMS ***

cocoapods-packager (1.3.0 ruby)
```

Everything I've read about pointing a gem to a specific git commit involves changing the gemfile, which I don't think I should do just yet...

What to do?

**Comment by neonichu** [comment]
Ah, right, I forgot that the dynamic library support wasn't released as a gem, yet. Since supporting CP 1.0 requires a few changes and it is due soon, I don't want to make any releases supporting 0.39 anymore.

**Comment by ExoticObjects** [comment]
I'm a bit confused. The version that supports dynamic libraries requires CP 1.0? But I've read elsewhere that that version isn't ready to deploy yet. In short, can I use the version of cocoapods-packager that supports dynamic frameworks, and if so, how?

thanks...

**Comment by ExoticObjects** [comment]
Got around to trying the latest version from git, getting this error:

```ruby
NoMethodError - undefined method `root_path' for nil:NilClass
/Users/****/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/builder.rb:52:in `link_embedded_resources'
/Users/****/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:147:in `perform_build'
/Users/****/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:79:in `build_in_sandbox'
/Users/****/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:92:in `block in build_package'
/Users/****/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:91:in `each'
/Users/****/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:91:in `build_package'
/Users/****/.rvm/gems/ruby-2.2.1/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:57:in `run'
/Users/****/.rvm/gems/ruby-2.2.1@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/****/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/****/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/****/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/****/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
```
This is the command I'm running:

`pod package test_sibling_dependencies_pod_a.podspec --embedded --force --dynamic`

It fails while building dynamic framework.

Any help would be sincerely appreciated!

**Comment by neonichu** [comment]
Sorry for this, it might be an incompatibility with CP 0.39. As said above, there's work underway to support CP 1.0 but no plans for digging deeper into 0.39 issues anymore.

**Comment by ExoticObjects** [comment]
Any timeframe for CP 1.0 support?

**Comment by neonichu** [comment]
I'll try to have it ready for the CP 1.0 final release.

**Comment by ExoticObjects** [comment]
So, is there currently any way to build dynamic frameworks? It doesn't work yet with 1.0, and there are problems with 0.39.0.

**Comment by ExoticObjects** [comment]
Hi! Now that Cocoapods 1.0 has been released, should this work?

To review, here's the problem I was having:

- I wanted to build a framework that could be a dependency of a pod. To avoid the `target has transitive dependencies that include static binaries` error, that framework would need to be dynamic.
- The version of Cocoapods-packager that worked with Cocoapods 0.39.0 didn't support creation of dynamic frameworks. And the code that did support dynamic frameworks wasn't ready. You said: "I'll try to have it ready for the CP 1.0 final release."

Can you let me know if it should work? Thanks...
