### ISSUE TITLE
pod package fail when there is a private repo dependency

### ISSUE THREAD

**Issue by allentofight** [CocoaPods/cocoapods-packager#140]
```ruby
Pod::Spec.new do |s|
  s.name             = "HusorClickLib"
  s.version          = "1.0.0"
  s.summary          = "A short description of HusorClickLib."

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!  
  s.description      = <<-DESC
                       Great Click lib
                       DESC

  s.homepage         = "http://git.husor.com.cn/Pods/HusorClick.git"
  s.license          = 'MIT'
  s.author           = { "guagua" => "junwei.wang@husor.com.cn" }
  s.source           = { :git => "/Users/ronaldo/Documents/husor/Pods/HusorClick"}

  s.platform     = :ios, '6.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**/*'
  s.resource_bundles = {
    'HusorClickLib' => ['Pod/Assets/*.png']
  }
  s.dependency 'BBZipLib', '~> 1.0.1'

end
```

the above BBZipLib is the private repo,But When I type the following command 

`pod package xx.podspec  --force`, it reports the following error 

`[!] Unable to find a specification for `BBZipLib (~> 1.0.1)` depended upon by `xxx`

when I type `pod search BBZipLib`, It gives me the right result

when I remove this line ` s.dependency 'BBZipLib', '~> 1.0.1' `, It works as expected,What's wrong with it ,it doesn't support dependency with private repo?

**Comment by allentofight** [comment]
It seems that it only recognize the spec in `~/.cocoapods/repos/master/Specs` ,When I copy my private spec to this directory ,I works! Is it a bug?

**Comment by neonichu** [comment]
Did you try using `--spec-sources` — you can use that to pass in additional repos.

**Comment by allentofight** [comment]
You mean this?
`pod package xx.podspec --spec-sources='http://xxxx' --force`

**Comment by neonichu** [comment]
Yep

**Comment by allentofight** [comment]
it woks!Thank you very much!!!

**Comment by neonichu** [comment]
👍

**Comment by crespoxiao** [comment]
@neonichu  thank you, that's help me.
