### ISSUE TITLE
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are:

### ISSUE THREAD

**Issue by XZoscar** [CocoaPods/cocoapods-packager#142]
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are:

when use pod package xxx.spec (swift)

**Comment by neonichu** [comment]
See #115
