### ISSUE TITLE
OpenSSL not part of the package

### ISSUE THREAD

**Issue by Boobby69** [CocoaPods/cocoapods-packager#145]
Hi, 

I'm trying to package a framework with OpenSSL library.
Below, you'll find a podspec with the problem. It's a fake one, but should reproduce the problem.
In my podspec, I have 5 dependencies. As I run the command `pod package Library.podspec --verbose`, I can see `-> Installing OpenSSL (1.0.208)` in the "Downloading dependencies" section. But, in the "Generating Pods project", there is no "Installing target OpenSSL iOS 7.1".

Then, when I push the podspec to my private repository, and integrate the generate framework to a project 'A', I have compilation errors pointing that OpenSSL is missing. And to fix this error, I had a dependency OpenSSL to my project 'A'. Is this a bug, or I'm missing something ?

Pod::Spec.new do |s|

  s.name         = "PodSpecName"
  s.version      = "5.2.0.15"
  s.summary      = "Summary"

  s.description  = <<-DESC
                   Long description
                   Copyright 2016
                   DESC

  s.homepage     = "http://www.website.com"
  s.license      = { :type => "MIT", :file => "License.txt" }
  s.author       = { "author" => "name@domain.com" }
  s.source       = { :git => "git URL", :tag => s.version }

  s.source_files  = "**/*.{h,m,c}"

  s.public_header_files = "Public APIs/**/*.h"

  s.requires_arc = true
  s.ios.deployment_target = '7.1'

  s.dependency 'OpenSSL', '~> 1.0.208'

end`

**Comment by neonichu** [comment]
Any `vendored_libraries` are currently not supported, see #26 — and OpenSSL uses that attribute.
