### ISSUE TITLE
Dynamic framework improvements

### ISSUE THREAD

**Issue by jtreanor** [CocoaPods/cocoapods-packager#148]
We will soon start shipping our SDK as a dynamic Framework but there are currently a few limitations.

I will happily fix these myself, but I am not sure exactly how.

1. The Bundle identifier in the produced `Info.plist` is always `org.cocoapods.{Pod Name}`. Any ideas how we could provide a custom value for this?
2. Would it be possible to include a`.dSYM` in packager's output? My understanding is that this could be useful for crash symbolication.

**Comment by segiddins** [comment]
There's an open issue on cocoapods for dsym support but it's not been implemented

**Comment by jtreanor** [comment]
Ah, thanks @segiddins.

Can you think of any way it could be possible to change the Bundle identifier?

For reference, the issue is here: https://github.com/CocoaPods/CocoaPods/issues/1698

**Comment by neonichu** [comment]
1. I think this is where CocoaPods itself sets the bundle identifier: <https://github.com/CocoaPods/CocoaPods/blob/3cf03bbd26ec830015bc8e7201c9d3a772a5b978/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb#L59>. It should be possible to change this build setting after Pod installation has finished and before building. We could make this a CLI option.

2. I'm pretty sure the `.dSYM` should already be generated as part of the build, it should just be a matter of locating and copying it. CocoaPods still wouldn't know anything about it, of course, but it could be used for manual symbolication of crash reports.

**Comment by jtreanor** [comment]
@neonichu That makes sense. I'll dig around a little and see what I find.

**Comment by jtreanor** [comment]
This concerns have now been addressed in #152 & #153.
