### ISSUE TITLE
Only the headers of 'vendored_frameworks' are copied into framework

### ISSUE THREAD

**Issue by xwang-phunware** [CocoaPods/cocoapods-packager#149]
I add a vendord framework `MyInternal.framework` like the below in my `MyProject.podspec`
....
`s.vendored_frameworks = 'Vendor/MyInternal.framework'`
....

And the `MyInternal.framework` structure like:
MyInternal.framework
|--Headers
|         |--MyInternal.h
|         |--Others.h
|--Resources
|         |--en.lproj
|--MyInternal 

Run `pod package MyProject.podspec xxx`, the `MyProject.framework` was successfully generated, but the library of MyInternal.framework wasn't embedded in it, and the final structure is like:
MyProject.framework
|--Modules
|         |--module.modulemap
|--Headers
|         |--MyProject.h
|         |--MyInternal
|                     |--MyInternal.h
|         |--Others.h
|--MyProject

I tried Cocoapods v0.39.0, v1.0.1 and Cocoapods-Packager v1.2.1, v1.3.0, v1.4.0, always have the problems:
1. The `MyInternal.framework/MyInternal` wasn't embedded to `MyProject.framework`
2. Why the `MyInternal.framework/Headers/xx` was embedded to `MyProject.framework`

**Comment by neonichu** [comment]
Sorry, `vendored_frameworks` are not yet support, see #26
