### ISSUE TITLE
About pod package cache

### ISSUE THREAD

**Issue by aolan** [CocoaPods/cocoapods-packager#157]
I found a problem , podspec document which has s.version field . For example, the current version number is 1.0 , I used the "pod package" to compile a static library , this time I modified the code , but also use the 1.0 , I found the new modifications will not be reflected

**Comment by neonichu** [comment]
Did you also modify the tag in your repo? `pod package` will always fetch the code from your repo, it does not use any local files.

**Comment by aolan** [comment]
I submitted a new code to "gitlab", delete "tag1.0", and then re-create the "tag1.0". This time to use the "cocoapods-package" to create a static library , just find the modified code is not added to the static library.

**Comment by aolan** [comment]
Yes，i have modifed the code and push to remote repo.

**Comment by neonichu** [comment]
You might also need to run `pod cache clean` as the old tag might still be cached by CocoaPods itself.

**Comment by aolan** [comment]
Thank you. After I used the "pod cache clean --all", really works. Thanks again.
