### ISSUE TITLE
package not support category?

### ISSUE THREAD

**Issue by mcmengchen** [CocoaPods/cocoapods-packager#167]
I use package to make a framework, but when I use it in my project. It can not call the category's method. How can I resolve it?

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the cocoapods-packager issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
