### ISSUE TITLE
Don't codesign

### ISSUE THREAD

**Issue by bamx23** [CocoaPods/cocoapods-packager#169]
Hi there!
Could you help me to figure up how to satisfy this line:
```ruby
if defined?(Pod::DONT_CODESIGN)
```

**Comment by segiddins** [comment]
Try adding
```
module Pod
 DONT_CODESIGN = true
end
```
To your podfile

**Comment by bamx23** [comment]
Which `Podfile`? Packager doesn't need one. I only have a `.spec` file.

**Comment by segiddins** [comment]
Then try putting it in your podspec. Sorry, I misread the repo the issue was in.

**Comment by bamx23** [comment]
I've tried your variant but it not works(packaging failed).
But this code works:
```ruby
Pod::DONT_CODESIGN = true
Pod::Spec.new do |s|
# ...
```
There is a warning now, but everything works fine:
```
/private/var/folders/yh/8kb6c3mn3pl33sp1msx8q_c5t129cs/T/cocoapods-7qtzo6ud/MyPod.podspec:1: warning: already initialized constant Pod::DONT_CODESIGN
MyPod.podspec:1: warning: previous definition of DONT_CODESIGN was here
```
I'll close the issue if it's ok.
