### ISSUE TITLE
operation  "--emeded"  "--dynamic"  

### ISSUE THREAD

**Issue by manwithstories** [CocoaPods/cocoapods-packager#189]
Can you tell me  the difference between  emeded framework  to  dynamic framework  ??

**Comment by manwithstories** [comment]
Can you tell me the difference between emeded framework and  dynamic framework ??

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
