### ISSUE TITLE
pod package failed: "Swift Language Version" build setting

### ISSUE THREAD

**Issue by ZeroJian** [CocoaPods/cocoapods-packager#210]
my project used swift language 

I tried to add to podspec:
 s.swift_version = '4.0'
 s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.0' }

but nothing change

***********************************************************************
pod package BM_Loggg.podspec --force
Analyzing dependencies
Fetching podspec for `BM_Loggg` from `BM_Loggg.podspec`
Downloading dependencies
Installing BM_Loggg (0.1.9)
Generating Pods project
Skipping User Project Integration
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
Building framework BM_Loggg (0.1.9) with configuration Release
Build command failed: xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited) PodsDummy_Pods_BM_Loggg=PodsDummy_PodPackage_BM_Loggg'  ARCHS='x86_64 i386 arm64 armv7 armv7s' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments' CONFIGURATION_BUILD_DIR=build clean build -configuration Release -target Pods-packager -project Pods/Pods.xcodeproj 2>&1
Output:
    2018-07-12 15:04:59.940 xcodebuild[35555:23553679] [MT] PluginLoading: Required plug-in compatibility UUID 426A087B-D3AA-431A-AFDF-F135EC00DE1C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    Build settings from command line:
        ARCHS = x86_64 i386 arm64 armv7 armv7s
        CONFIGURATION_BUILD_DIR = build
        GCC_PREPROCESSOR_DEFINITIONS = $(inherited) PodsDummy_Pods_BM_Loggg=PodsDummy_PodPackage_BM_Loggg
        OTHER_CFLAGS = -fembed-bitcode -Qunused-arguments

    === CLEAN TARGET BM_Loggg OF PROJECT Pods WITH CONFIGURATION Release ===

    Check dependencies
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

    ** CLEAN FAILED **

    The following build commands failed:
    	Check dependencies
    (1 failure)
    === BUILD TARGET BM_Loggg OF PROJECT Pods WITH CONFIGURATION Release ===

    Check dependencies
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

    ** BUILD FAILED **

    The following build commands failed:
    	Check dependencies
    (1 failure)
***********************************************************************

my new podspec 

Pod::Spec.new do |s|
  s.name         = "BM_Loggg"
  s.version      = "0.1.9"
  s.summary      = "xxx"
  s.description  = xxx
  s.homepage     = "xxx"
  s.license      = { :type => 'MIT', :file => 'LICENSE' }
  s.author       = { "xxx" => "xxx" }
  s.source       = { :git => "git@gitlab.xxx/BM_Loggg.git", :tag => "#{s.version}" }
  s.platform     = :ios, "8.0"
  s.swift_version = '4.0'
  #s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.0' }
  s.public_header_files = 'Sources/*.h'
  s.source_files  = 'Sources/**/*.{swift,h}'
  s.framework = "UIKit"
  s.requires_arc = true
end

**Comment by segiddins** [comment]
```ruby
Pod::Spec.new do |s|
s.name = "BM_Loggg"
s.version = "0.1.9"
s.summary = "xxx"
s.description = xxx
s.homepage = "xxx"
s.license = { :type => 'MIT', :file => 'LICENSE' }
s.author = { "xxx" => "xxx" }
s.source = { :git => "git@gitlab.xxx/BM_Loggg.git", :tag => "#{s.version}" }
s.platform = :ios, "8.0"
s.public_header_files = 'Sources/.h'
s.source_files = 'Sources/**/.{swift,h}'
s.framework = "UIKit"
s.requires_arc = true
end

```

doesnt seem to contain a swift version

**Comment by ZeroJian** [comment]
@segiddins  this is original spec.  my new spec contain  s.swift_version = '4.0'
s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.0' } , but nothing change

**Comment by ZeroJian** [comment]
s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4' }  no push to git

**Comment by pat750207** [comment]
I have the same issue, how to fix?

**Comment by DmitryPR** [comment]
As I understand if the podspec is relying on other dependencies, those should include s.swift_version. 

s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.2' } is being ignored for 3rd party dependencies, is there any way to handle this?
