### ISSUE TITLE
xxxnib with mutable output but no other virtual output node

### ISSUE THREAD

**Issue by bart1989** [CocoaPods/cocoapods-packager#230]
I use xib to build interface in my project, then I want to make a framework.
this is the command:
pod package RankModule.podspec --force --dynamic --no-mangle --spec-sources=https://git.mygit.com/myproject/MySpecRepo.git,https://github.com/CocoaPods/Specs.git

the error:
 Build system information
    error: invalid task ('StripNIB /var/folders/v0/jkyt1dhn6ws8l57lnscjzlsm0000gp/T/cocoapods-bspd6xq8/Pods/Static/build/RightPopCollectionHeader.nib') with mutable output but no other virtual output node (in target 'RankModule')

how to resolve it?

**Comment by bart1989** [comment]
i config the xib file in podspec to reslove.

**Comment by rahib110** [comment]
> i config the xib file in podspec to reslove.

Hi, could you please let me know how you fixed this..I am facing the same issue. 
I have created a pod that is working in it's example project. but when I'm trying to configure this with some other external project it throws errors. 

error:
1: invalid task ('StripNIB /Users/mrhb/Library/Developer/Xcode/DerivedData/EyesWideProject-dzvkzhxcjfeyssbvaecqlzazejyw/Build/Products/Debug\ with\ real\ server-iphonesimulator/ios-pdpa/CheckboxRightLabelsView.nib') with mutable output but no other virtual output node (in target 'ios-insightthispod')
