### ISSUE TITLE
xcode14 BUILD FAILED

### ISSUE THREAD

**Issue by chakbun** [CocoaPods/cocoapods-packager#282]
after updated to xcode14，build failed!!!

 error: The armv7 architecture is deprecated. You should update your ARCHS build setting to remove the armv7 architecture. (in target xxxx)
    error: The armv7s architecture is deprecated. You should update your ARCHS build setting to remove the armv7s architecture. (in target xxxx)

---->  how can i update my archs setting ?

**Comment by leoniralves** [comment]
Same problem here 😞

**Comment by chakbun** [comment]
> Same problem here 😞

it works ok after i did something below

update /Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/builder.rb


```ruby
def ios_build_options
      "ARCHS=\'$(ARCHS_STANDARD)\' OTHER_CFLAGS=\'-fembed-bitcode -Qunused-arguments\'"
end
````

**Comment by ytdxxt10** [comment]
> > Same problem here 😞
> 
> it works ok after i did something below
> 
> update /Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/builder.rb
> 
> ```ruby
> def ios_build_options
>       "ARCHS=\'$(ARCHS_STANDARD)\' OTHER_CFLAGS=\'-fembed-bitcode -Qunused-arguments\'"
> end
> ```

same problem  
but I try write builder.rb   error:The file “builder.rb” could not be unlocked. Could not add write permission to the file because you do not own it. Try modifying the permissions of the file in the Finder or Terminal.

**Comment by chakbun** [comment]
> > > Same problem here 😞
> > 
> > 
> > it works ok after i did something below
> > update /Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/builder.rb
> > ```ruby
> > def ios_build_options
> >       "ARCHS=\'$(ARCHS_STANDARD)\' OTHER_CFLAGS=\'-fembed-bitcode -Qunused-arguments\'"
> > end
> > ```
> 
> same problem but I try write builder.rb error:The file “builder.rb” could not be unlocked. Could not add write permission to the file because you do not own it. Try modifying the permissions of the file in the Finder or Terminal.


make a copy to Desktop and you can write it, then replace original one in lib with sudo cmd

**Comment by benmaxyoung** [comment]
> > Same problem here 😞
> 
> it works ok after i did something below
> 
> update /Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/builder.rb
> 
> ```ruby
> def ios_build_options
>       "ARCHS=\'$(ARCHS_STANDARD)\' OTHER_CFLAGS=\'-fembed-bitcode -Qunused-arguments\'"
> end
> ```

Perfect!

**Comment by ws745630** [comment]
```
xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited) PodsDummy_Pods_CMTest=PodsDummy_PodPackage_CMTest'  
ARCHS='$(ARCHS_STANDARD)' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments' CONFIGURATION_BUILD_DIR=build 
clean build -configuration Release -target Pods-packager -project Pods/Pods.xcodeproj 
User defaults from command line:
        IDEPackageSupportUseBuiltinSCM = YES
    
    Build settings from command line:
        ARCHS = $(ARCHS_STANDARD)
        CONFIGURATION_BUILD_DIR = build
        GCC_PREPROCESSOR_DEFINITIONS = $(inherited) PodsDummy_Pods_CMTest=PodsDummy_PodPackage_CMTest
        OTHER_CFLAGS = -fembed-bitcode -Qunused-arguments
```
An error occurred when I executed the packaging command after modification

**Comment by Jackie-Lee-Mr** [comment]
How i resolved it ? can you give me  help?

Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild "GCC_PREPROCESSOR_DEFINITIONS=$(inherited) PodsDummy_Pods_MJRefresh=PodsDummy_PodPackage_MJRefresh" "ARCHS=x86_64 i386 arm64 armv7 armv7s" "OTHER_CFLAGS=-fembed-bitcode -Qunused-arguments" CONFIGURATION_BUILD_DIR=build clean build -configuration Release -target Pods-packager -project Pods/Pods.xcodeproj

    User defaults from command line:
        IDEPackageSupportUseBuiltinSCM = YES

    Build settings from command line:
        ARCHS = x86_64 i386 arm64 armv7 armv7s
        CONFIGURATION_BUILD_DIR = build
        GCC_PREPROCESSOR_DEFINITIONS = $(inherited) PodsDummy_Pods_MJRefresh=PodsDummy_PodPackage_MJRefresh
        OTHER_CFLAGS = -fembed-bitcode -Qunused-arguments


    ** CLEAN SUCCEEDED **

    Computing target dependency graph and provisioning inputs

    Create build description
    Build description signature: 7b4e838a194b4acbd7e1b6599da7f5f2
    Build description path: /var/folders/8j/v_ncg3bj57n4f8nznshn8vph0000gn/T/cocoapods-icckj30f/Pods/../build/XCBuildData/7b4e838a194b4acbd7e1b6599da7f5f2-desc.xcbuild

    warning: Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning
    error: The armv7 architecture is deprecated. You should update your ARCHS build setting to remove the armv7 architecture. (in target 'Pods-packager' from project 'Pods')
    error: The armv7s architecture is deprecated. You should update your ARCHS build setting to remove the armv7s architecture. (in target 'Pods-packager' from project 'Pods')
    error: The armv7 architecture is deprecated. You should update your ARCHS build setting to remove the armv7 architecture. (in target 'MJRefresh' from project 'Pods')
    error: The armv7s architecture is deprecated. You should update your ARCHS build setting to remove the armv7s architecture. (in target 'MJRefresh' from project 'Pods')
    ** BUILD FAILED **

**Comment by Jackie-Lee-Mr** [comment]
> Same problem here 😞

can you solve it ?

**Comment by Jackie-Lee-Mr** [comment]
> > > Same problem here 😞
> > 
> > 
> > it works ok after i did something below
> > update /Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/builder.rb
> > ```ruby
> > def ios_build_options
> >       "ARCHS=\'$(ARCHS_STANDARD)\' OTHER_CFLAGS=\'-fembed-bitcode -Qunused-arguments\'"
> > end
> > ```
> 
> same problem but I try write builder.rb error:The file “builder.rb” could not be unlocked. Could not add write permission to the file because you do not own it. Try modifying the permissions of the file in the Finder or Terminal.
do you solve ?

**Comment by ytdxxt10** [comment]
I didn't fix it at the time, I switched to a computer with xcode and a lower system and dealt with it temporarily



> > > > Same problem here 😞
> > > 
> > > 
> > > it works ok after i did something below
> > > update /Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/builder.rb
> > > ```ruby
> > > def ios_build_options
> > >       "ARCHS=\'$(ARCHS_STANDARD)\' OTHER_CFLAGS=\'-fembed-bitcode -Qunused-arguments\'"
> > > end
> > > ```
> > 
> > 
> > same problem but I try write builder.rb error:The file “builder.rb” could not be unlocked. Could not add write permission to the file because you do not own it. Try modifying the permissions of the file in the Finder or Terminal.
> > do you solve ?



> > > > Same problem here 😞
> > > 
> > > 
> > > it works ok after i did something below
> > > update /Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/builder.rb
> > > ```ruby
> > > def ios_build_options
> > >       "ARCHS=\'$(ARCHS_STANDARD)\' OTHER_CFLAGS=\'-fembed-bitcode -Qunused-arguments\'"
> > > end
> > > ```
> > 
> > 
> > same problem but I try write builder.rb error:The file “builder.rb” could not be unlocked. Could not add write permission to the file because you do not own it. Try modifying the permissions of the file in the Finder or Terminal.
> > do you solve ?

**Comment by zd198666** [comment]
> 

can you solve it ?

**Comment by zd198666** [comment]
> 

can you solve it ?
