### ISSUE TITLE
podspec with path source does not build

### ISSUE THREAD

**Issue by smistry-toushay** [CocoaPods/cocoapods-packager#32]
I'm trying to avoid committing to Git prior to building a .framework using CocoaPods packager for local testing by setting `s.source = { :path => <path to source folder> }` however I get the following error:

```
$ pod package PathSpecTest.podspec
Analyzing dependencies
Fetching podspec for `PathSpecTest` from `PathSpecTest.podspec`
Downloading dependencies
Installing PathSpecTest (0.1.0)

[!] Error installing PathSpecTest
[!] Attempt to read non existent folder `/private/var/folders/lt/1cy1pl9j13q2tmv_2bc538pr0000gn/T/cocoapods-pvo5xiq5/Pods/PathSpecTest`.
```

I've create a sample here: https://github.com/smistry-toushay/cocoapods-packager-path-spec-test

The value for `path` in the podspec needs to be replaced with where the sample repo is cloned on your Mac.

**Comment by genkobar** [comment]
Sorry for kicking a two-year dead horse, but why does the [CocoaPods Guide](https://guides.cocoapods.org/syntax/podspec.html#source) state that ```:path``` is a valid key for ```source``` when the everyone in this discussion agrees that it isn't?

Pod spec lint currently fails with the error
> ERROR | [iOS] unknown: Encountered an unknown error (Unsupported download strategy `{:path=>"/abcd/efgh/ijk"}`.) during validation.

so I guess the guide must be mistaken.

![podspec_source_path](https://cloud.githubusercontent.com/assets/4376473/21648919/ab63ea7c-d297-11e6-8038-db42c044b71a.jpg)

**Comment by karosLi** [comment]
why {:path=>"/abcd/efgh/ijk"}. is not supported?

**Comment by shawnXiao** [comment]
In the CocoaPods newest document, the Supported Keys have no ':path'

![image](https://user-images.githubusercontent.com/1880567/40961360-ed726766-68d4-11e8-9b61-b64ab1fa8271.png)

**Comment by segiddins** [comment]
> In the CocoaPods newest document, the Supported Keys have no ':path'

Because it is not a support key for the `source` attribute in a podspec

**Comment by alexlee002** [comment]
@segiddins  using local path as a private pod is a very useful feature,  which can help to separate modules in a lightweight mechanism。

**Comment by mtruszko** [comment]
@alexlee002 You could use { :http => 'file://localhost/Users/[Home]/Path/To/Zip/Pod.zip' }
