### ISSUE TITLE
Generate module map if umbrella header is present

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/cocoapods-packager#55]

**Comment by blakewatters** [comment]
@neonichu Is this stuff stable? Time for a new release?

**Comment by segiddins** [comment]
I believe @neonichu was waiting until cocoapods 0.36 is released?

**Comment by blakewatters** [comment]
Cool I’ll try binding against the CP pre-release and HEAD on here and see what happens

**Comment by neonichu** [comment]
Yep, the plan was to release when 0.36 is out - thanks for testing it!

**Comment by blakewatters** [comment]
Shipped an internal LayerKit release today without issues. Should be dropping final tomorrow. :+1:

**Comment by neonichu** [comment]
🎉
