### ISSUE TITLE
Provide symbol mangling for dependencies

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/cocoapods-packager#6]
CocoaPods should be usable for companies that want to distribute binary builds (for the purpose of keeping the source private) of their pods directly, while still maintaining the dependency resolution flexibility we have now from raw source.

The packager should be able to package up _just_ the source files specified in the podspec, without including other dependencies specified in the spec. In this manner, there will be no risk of duplicated symbols if other pods rely on the same dependencies.

There should also be a way for the packager to turn the 'source' podspec into a 'binary' podspec that can be pushed to trunk.

**Comment by Whirlwind** [comment]
Do nobody agree with me?
