### ISSUE TITLE
I want to generate a static lib ,but get some errors as follow.

### ISSUE THREAD

**Issue by sevenfeng012** [CocoaPods/cocoapods-packager#68]
seven:AFFacebookLib fengzhijian$ pod package AFFacebookLib.podspec --library --force
Analyzing dependencies
Fetching podspec for `AFFacebookLib` from `AFFacebookLib.podspec`
Downloading dependencies
Installing AFFacebookLib (0.1.0)
Generating Pods project
Building static library
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: Pods/build/package.a (No such file or directory)
seven:AFFacebookLib fengzhijian$

**Comment by neonichu** [comment]
`libtool: unrecognized option `-static'`

This suggests that you have a non- libtool in your PATH, the following errors are caused by that. Changing your PATH to reference the correct libtool should resolve this.
