### ISSUE TITLE
packager plugin not found with local `rake install`

### ISSUE THREAD

**Issue by mszupke** [CocoaPods/cocoapods-packager#75]
Hi,

I have the same problem which was described here:
https://github.com/CocoaPods/cocoapods-packager/issues/71
I tried to install 1.1.2 version from source but pod package isn't visible. Can you give me some advice how to properly install this version from source, or can you publish this version to cocoapods repository?

**Comment by neonichu** [comment]
`rake install` from your working copy should be all you need.

**Comment by mszupke** [comment]
After rake install I have cocoapods-package on installed gem list:

cocoapods (0.36.3)
cocoapods-core (0.36.3)
cocoapods-downloader (0.9.0)
cocoapods-packager (1.1.2)
cocoapods-plugins (0.4.2)
cocoapods-trunk (0.6.0)
cocoapods-try (0.4.3)

but when I try to run pod package then I get an error:

[!] Unknown command: `package`
Did you mean: update


On commands list i don't have package option

**Comment by neonichu** [comment]
This most probably means that the `pod` in your `PATH` is not using the `GEM_HOME` used by the `gem` in your `PATH`. 

```
$ which pod
/Users/boris/Software/ruby-200/bin/pod
$ which gem
/Users/boris/Software/ruby-200/bin/gem
$ echo $GEM_HOME

```

Unless you explicitly know that they should be different, those two directories should be the same and `GEM_HOME` should be empty.

**Comment by mszupke** [comment]
This is my environment:

MacBook-Air-Marcin:blinky-module-ios mszupke$ which pod
/usr/bin/pod
MacBook-Air-Marcin:blinky-module-ios mszupke$ which gem
/usr/bin/gem
MacBook-Air-Marcin:blinky-module-ios mszupke$ echo $GEM_HOME

MacBook-Air-Marcin:blinky-module-ios mszupke$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14
  - RUBY VERSION: 2.0.0 (2014-05-08 patchlevel 481) [universal.x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-14
  - GEM PATHS:
     - /Library/Ruby/Gems/2.0.0
     - /Users/mszupke/.gem/ruby/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/

**Comment by mszupke** [comment]
This is my environment:

MacBook-Air-Marcin:~ mszupke$ which pod
/usr/bin/pod
MacBook-Air-Marcin:~ mszupke$ which gem
/usr/bin/gem
MacBook-Air-Marcin:~ mszupke$ echo $GEM_HOME

MacBook-Air-Marcin:~ mszupke$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14
  - RUBY VERSION: 2.0.0 (2014-05-08 patchlevel 481) [universal.x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-14
  - GEM PATHS:
     - /Library/Ruby/Gems/2.0.0
     - /Users/mszupke/.gem/ruby/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/

**Comment by neonichu** [comment]
Generally looks good to me, I can't say what's going wrong there, sorry.

**Comment by mszupke** [comment]
Maybe if you put packager 1.1.2 to cocoapods repository this error will not appear?

**Comment by neonichu** [comment]
Feel free to open a PR with the change, then it can eventually be shipped to rubygems.
