### ISSUE TITLE
Please add examples to documentation

### ISSUE THREAD

**Issue by Cross22** [CocoaPods/cocoapods-packager#76]
According to pod package --help it should be possible to specify a different source as second argument. I have not been able to get that to work ("Unable to find a podspec with path or name.") and there is no documentation on how this should be done.

**Comment by neonichu** [comment]
This works just as documented for me:

```bash
$ pod package CPDColors.podspec yolo
[...]
$ grep yolo CPDColors-0.1.0/*.podspec
CPDColors-0.1.0/CPDColors.podspec:  s.source = yolo
```

Please report back with a reproducible case if this keeps being a problem.
