### ISSUE TITLE
Ability to specify "umbrella" header name on the generated module_map file

### ISSUE THREAD

**Issue by cvasilak** [CocoaPods/cocoapods-packager#77]
Hi there,

thanks for your work on the plugin, it truly automates most of cumbersome scripts that had to maintain.

I have a question on an issue I bumped in. According the [source code](https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/builder.rb#L115-L123) the ```module_map``` generated file  specifies an umbrella header that defaults to the ```spec.name```. Is there any way that this behaviour can be overridden (e.g through a command line option), so the user can specify the name of the umbrella header  in cases where spec.name != default_header_name?

**Comment by neonichu** [comment]
Currently, this is not possible. 

I'm thinking the best way to achieve it would be tapping into the existing `module_map` attribute in the podspec: <https://guides.cocoapods.org/syntax/podspec.html#module_map> - while this doesn't apply for the static library builds cp-packager does, it could ensure that the same module map is used no matter the integration strategy.

If you have time to contribute, I'd love a PR for this.

**Comment by cvasilak** [comment]
thank you @neonichu for your quick reply and hint. Let me have a look at and ping back.

**Comment by neonichu** [comment]
Implemented in #79
