### ISSUE TITLE
Include dependencies frameworks to package

### ISSUE THREAD

**Issue by sidorov-panda** [CocoaPods/cocoapods-packager#81]
Hello,
I`m trying to include ShareKit pod to my Framework, but always get something like

    In file included from /var/folders/hv/j5vtrx9j1m70g9p4xjh5ymhm0000gp/T/cocoapods-fqj7cuu2/Pods/ShareKit/Classes/ShareKit/Sharers/Services/Dropbox/SHKDropbox.m:9:
    /var/folders/hv/j5vtrx9j1m70g9p4xjh5ymhm0000gp/T/cocoapods-fqj7cuu2/Pods/ShareKit/Classes/ShareKit/Sharers/Services/Dropbox/SHKDropbox.h:14:9: fatal error: 'DropboxSDK/DropboxSDK.h' file not found
    #import <DropboxSDK/DropboxSDK.h>
            ^
    1 error generated.

My pod spec is looking like:
Pod::Spec.new do |s|
  s.name         = "MySDK"
  s.version      = "0.0.1"
  s.summary      = "A short description of MySDK."
  s.homepage     = "http://MySDK.io"
  s.license      = "MIT (example)"
  s.platform     = :ios, "8.0"
  s.source       = { :git => "...", :tag => "0.0.1" }
  s.source_files  = "MySDK", "MySDK/*.{h,m}"
  s.exclude_files = "Classes/Exclude"
  s.requires_arc = true

  #s.xcconfig = { "HEADER_SEARCH_PATHS" => "$(SDKROOT)/ShareKit/Classes/ShareKit/Sharers/Services/" }
  s.dependency "ShareKit"

end

How can I fix it?
Thanks

**Comment by neonichu** [comment]
Looks like Dropbox is a vendored framework, this is currently not supported by the packager, see #26
