### ISSUE TITLE
Use target defined in Xcworkspace in podspec

### ISSUE THREAD

**Issue by WoodySlum** [CocoaPods/cocoapods-packager#83]
Hello,

Would it be possible (or maybe it's already the case) to use Xcworkspace targets to build framwork ?

Thank you

**Comment by neonichu** [comment]
I'm unsure what you mean by that. The packager takes a podspec and creates a "fake framework" from its build result.

**Comment by WoodySlum** [comment]
In fact my company created a SDK with many build tricks (e.g. private frameworks).
Today, we're using specific target on our SDK xcodeproj to build the .framework correctly.

But ...

We embedded external librairies into our SDK, and our customer use the same librairies which creates collisions.
I would like to use Cocoapods Packager to enable prefixes and avoiding those collisions.

The more simple today would be to specify in my podspec the .xcodeproj and the target I would like to build.

**Comment by neonichu** [comment]
Dealing with existing Xcode projects is out of scope for this plugin, it's purpose is solely to package podspecs.

Check out <https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/mangle.rb> for how the symbol mangling is done, from that you should be able to come up with a solution for your problem.
