### ISSUE TITLE
Mangling and -ObjC

### ISSUE THREAD

**Issue by WoodySlum** [CocoaPods/cocoapods-packager#84]
I started writting a podspec for my library ; the goal was to avoid embbed library collision.
The Cocoapods packager built successfully my library into a .framework, but I'm experiencing an issue :
As I'm using categories, I had to add the -ObjC flag on the final project (I mean the project who embed my library), according to this post : http://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library

The result is I cannot add the same library in other versions in the final project (duplicate symbols for achitecture).

Is there any workaround to manage conflicts ? Or maybe I didn't well understand mangle's goal ?

**Comment by neonichu** [comment]
No mangling is performed for category methods, see #52
