### ISSUE TITLE
Packager failing if bundling external library

### ISSUE THREAD

**Issue by jjramos-developer** [CocoaPods/cocoapods-packager#87]
I have created a library that has 3 dependencies. Two are specified as such in the podspec and the third one is [Mantle] (https://github.com/Mantle/Mantle) where I have forked the repo, pre-fixed all the files and included them in the main target of my static library.

The project in Xcode builds successfully but when using cocoapods packager I get this error
```
/var/folders/28/q6n0xfd90_1gnl6xpy19lxsr0000gn/T/cocoapods-mv46buuc/Pods/...(rest of the path deleted) 
fatal error: 'MTLModel.h' file not found
    #import "MTLModel.h"
            ^
```

I have checked my code over and over and there is no reference to `MTLModel.h`. The pre-fixed version is always in use.

If I add [Mantle] (https://github.com/Mantle/Mantle) to the Podfile and specidy it as a dependency in my podspec it builds ok.

Any idea why I am getting this error? I've also tried deleting the temporary filed referenced in the fatal error and using the `--force` option but still no success.

Many thanks.

**Comment by neonichu** [comment]
The packager knows nothing about your custom projects or Podfiles. To use a fork of Mantle when packaging, you would need to put a podspec for the fork in your own spec repo and then reference that via `--sources`.
