### ISSUE TITLE
Symbols of pod dependencies are not mangled

### ISSUE THREAD

**Issue by virl** [CocoaPods/cocoapods-packager#89]
I've succesfully build framework. But when I look into its symbol table via "nm -gU", I see that symbols of its dependencies are not mangled:

```
Underdark(Pods-ArrayUtils-dummy.o):
00000000000005d0 S _OBJC_CLASS_$_PodUnderdark_PodsDummy_Pods_ArrayUtils
00000000000005a8 S _OBJC_METACLASS_$_PodUnderdark_PodsDummy_Pods_ArrayUtils
```

How to enabled mangling of them so they will not interfere with same symbols in the main app?

**Comment by segiddins** [comment]
That is "mangled", by the prefix of `PodUnderdark`, no?

**Comment by virl** [comment]
Oh, yes. But when I linking resulting framework to main App, it still complains like this:
```
objc[43542]: Class PodsDummy_Pods_ArrayUtils is implemented in both /Users/virl/Library/Developer/Xcode/DerivedData/Solidarity-fgodlswvagsujbgdoaomffcvkajy/Build/Products/Debug-iphonesimulator/Underdark.framework/Underdark and /Users/virl/Library/Developer/CoreSimulator/Devices/BAA627A7-5F77-4128-9DAE-2B315BBDEFBA/data/Containers/Bundle/Application/BEC66ABA-6A20-4A1A-914E-16C2904EEB23/Solidarity.app/Solidarity. One of the two will be used. Which one is undefined.
```

**Comment by virl** [comment]
Also, should I specify --embedded key? What does it do?
I just want to build dynamic framework.

**Comment by neonichu** [comment]
I'm assuming `ArrayUtils` is a category? Those won't get mangled. Also the packager builds static fake frameworks, dynamic frameworks are not yet implemented.

**Comment by virl** [comment]
Yes, it is a category. Thanks!

Btw, do you know how can I mangle dynamic Cocoa Touch Framework target?

**Comment by neonichu** [comment]
You can have a look at the mangling implementation of the packager and adopt it: https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/mangle.rb 

Or you could try making a PR for adding dynamic frameworks support, I'd be happy to help with that.

**Comment by virl** [comment]
Thanks.
