### ISSUE TITLE
Building framework with cocoapods 0.38.0

### ISSUE THREAD

**Issue by ajitam** [CocoaPods/cocoapods-packager#90]
Hi,

since I've updated to cocoapods 0.38 when building framework, .a file doesn't builds and I'm left with only public headers

running

```
pod _0.37.1_ package myLib.podspec
```

works as usual

**Comment by pellet** [comment]
I second this issue... sticking to building with 0.37.2, thanks for the heads up... I couldn't work out why the binary wasn't building :/

**Comment by pellet** [comment]
just tested cocoapods 0.38.2 and it's still broken.

**Comment by xslim** [comment]
relating my issue from CocoaPods https://github.com/CocoaPods/CocoaPods/issues/3782

with `0.38.0+` instead of `Pods-MyLib` scheme, `MyLib` scheme is created

**Comment by neonichu** [comment]
Yes, cp-packager does not support 0.38.x, yet.

**Comment by ajitam** [comment]
Does `gem update` updates cocoapods-package ? I did this but it still doesn't work

**Comment by neonichu** [comment]
There has been no new release, yet.

**Comment by neonichu** [comment]
Released 1.3.0 now, which supports/requires CocoaPods 0.38.x

**Comment by ajitam** [comment]
✓ build
✓ run
✓ test

= :+1: works
