### ISSUE TITLE
Dependency from private repo not found

### ISSUE THREAD

**Issue by navratill** [CocoaPods/cocoapods-packager#93]
When I am using dependency on company's library from our private repo, packager return error:
```
[!] Unable to find a specification for `lib-b (>= 1.0)` depended upon by `lib-a`
```
private repo is added into cocopapods (pod repo - shows it)

So does packager support local repos as well?

Thanks

**Comment by kylef** [comment]
`pod package` takes `--spec-sources`, please consult the `--help` option for more information.

```shell
$ pod package --help
```
