### ISSUE TITLE
duplicate symbol

### ISSUE THREAD

**Issue by numbbuaa** [CocoaPods/cocoapods-packager#94]
In original frameworkPod.podspec, frameworkPod has dependency below
    s.dependency 'PodA'
while, in PodA.podspec, PodA has dependency below
    s.dependency 'PodB'
Then, I use cocoapods-package to generate a framework library from frameworkPod.podspec

In my project, I have Podfile like
    pod 'frameworkPod'
    pod 'PodB'

'pod update' and build, I meet error
duplicate symbol(something in PodB) _XXXX in:

**Comment by neonichu** [comment]
This is clearly to unspecific to work with. My best guess would be that PodB includes categories, which are not mangled by cp-packager, see #52. If that is not the case, please provide information on how to actually reproduce this, then we can reopen this issue.

**Comment by numbbuaa** [comment]
@neonichu in my case, frameworkPod has dependency 's.dependency 'PodA'', PodA has dependency 's.dependency 'NIAttributedLabel'', in my project, use Podfile like
pod 'frameworkPod', :path => "../frameworkPod-0.1.0"'
pod 'NIAttributedLabel'
'pod update' and build, I meet error
duplicate symbol _NIDebugAssertionsShouldBreak in:
    /Users/xxx/Library/Developer/Xcode/DerivedData/frameworkPod-gztwxwexoihbdnfuqdglguntimkm/Build/Products/Debug-iphonesimulator/libPods-frameworkPod-NIAttributedLabel.a(NIAttributedLabel.o)
    /Users/xxx/frameworkPod-0.1.0/ios/frameworkPod.framework/somePod(NIAttributedLabel.o) 'NIDebugAssertionsShouldBreak' here is a variable define in 'NIAttributedLabel.m' like below
BOOL NIDebugAssertionsShouldBreak = YES;

**Comment by neonichu** [comment]
This looks like as if that variable should be static so that duplicates are allowed.

**Comment by numbbuaa** [comment]
@neonichu There is a question that NIAttributedLabel is a third part pod library, so I cannot modify its source code.Should this kind variables be mangled by  cocoapods-packager?

**Comment by kylef** [comment]
@numbbuaa NIAttributedLabel is open source so you could create a pull request solving the problem with their pod.

https://github.com/NimbusKit/attributedlabel/tree/master/src

**Comment by numbbuaa** [comment]
@neonichu @kylef Is there a option to generate a framework exclude source code of dependency pod.
